### ISSUE TITLE
What license did you intend to release this under?

### ISSUE THREAD

**Issue by toddobryan** [adrianwalker/multiline-string#1]
Would love to use this for some tests, but don't want to infringe your copyright.

**Comment by adrianwalker** [comment]
Hi Todd,

All the code I release is Public Domin.  Please feel free to use, modify and distribute my code in any way you like without any restrictions.

See here for more details:
http://www.adrianwalker.org/2011/12/java-multiline-string.html

Cheers

Adrian

**Comment by toddobryan** [comment]
Thanks!
