### ISSUE TITLE
multiline-string:jar download from maven central

### ISSUE THREAD

**Issue by devMls** [adrianwalker/multiline-string#4]
Hi,, 

at first this library and plugin looks amazing!!

I can't achieve download the jar for maven:

Failed to execute goal on project myproject: Could not resolve dependencies for project myproject:war:1.0-SNAPSHOT: Could not find artifact org.adrianwalker:multiline-string:jar:0.2.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]

where can i found the jar?

**Comment by adrianwalker** [comment]
Hi  devMIs

I'm not aware of any repositories, maven central or 3rd party, that are hosting the precompiled jar.  I suggest you build it yourself from source and install it into you local repository or companies repository.

Cheers

**Comment by javatlacati** [comment]
Hey bro, I know a way to do it, but you should first solve issue #5

**Comment by devMls** [comment]
For anybody with this problem, i found this:

https://jitpack.io/

Allow import github repository like maven dependency
